### ISSUE TITLE
Fatal error on each graphQL request

### ISSUE THREAD

**Issue by Fooriva** [thecodingmachine/graphql-controllers#4]
Fatal error: Uncaught Error: Call to undefined method Roave\BetterReflection\Reflection\ReflectionType::getTypeObject() in /var/www/html/vendor/thecodingmachine/graphql-controllers/src/ControllerQueryProvider.php on line 111
Error: Call to undefined method Roave\BetterReflection\Reflection\ReflectionType::getTypeObject() in /var/www/html/vendor/thecodingmachine/graphql-controllers/src/ControllerQueryProvider.php on line 111

We get this error anytime we want to execute graphql request since the last release.

**Comment by moufmouf** [comment]
Closed by #5.
